// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $admintotallynotguessable_layout from "./routes/admintotallynotguessable/_layout.tsx";
import * as $admintotallynotguessable_codename from "./routes/admintotallynotguessable/codename.tsx";
import * as $admintotallynotguessable_multichoice from "./routes/admintotallynotguessable/multichoice.tsx";
import * as $admintotallynotguessable_truefalse from "./routes/admintotallynotguessable/truefalse.tsx";
import * as $admintotallynotguessable_written from "./routes/admintotallynotguessable/written.tsx";
import * as $api_codename from "./routes/api/codename.ts";
import * as $api_counter from "./routes/api/counter.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_savedb from "./routes/api/savedb.ts";
import * as $api_score from "./routes/api/score.ts";
import * as $api_ws from "./routes/api/ws.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Client from "./islands/Client.tsx";
import * as $Codename from "./islands/Codename.tsx";
import * as $Multichoice from "./islands/Multichoice.tsx";
import * as $Phase from "./islands/Phase.tsx";
import * as $ScoreCounter from "./islands/ScoreCounter.tsx";
import * as $Select from "./islands/Select.tsx";
import * as $TeamView from "./islands/TeamView.tsx";
import * as $Truefalse from "./islands/Truefalse.tsx";
import * as $_settings from "./islands/_settings.ts";
import * as $newclient from "./islands/newclient.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/admintotallynotguessable/_layout.tsx":
      $admintotallynotguessable_layout,
    "./routes/admintotallynotguessable/codename.tsx":
      $admintotallynotguessable_codename,
    "./routes/admintotallynotguessable/multichoice.tsx":
      $admintotallynotguessable_multichoice,
    "./routes/admintotallynotguessable/truefalse.tsx":
      $admintotallynotguessable_truefalse,
    "./routes/admintotallynotguessable/written.tsx":
      $admintotallynotguessable_written,
    "./routes/api/codename.ts": $api_codename,
    "./routes/api/counter.ts": $api_counter,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/savedb.ts": $api_savedb,
    "./routes/api/score.ts": $api_score,
    "./routes/api/ws.ts": $api_ws,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Client.tsx": $Client,
    "./islands/Codename.tsx": $Codename,
    "./islands/Multichoice.tsx": $Multichoice,
    "./islands/Phase.tsx": $Phase,
    "./islands/ScoreCounter.tsx": $ScoreCounter,
    "./islands/Select.tsx": $Select,
    "./islands/TeamView.tsx": $TeamView,
    "./islands/Truefalse.tsx": $Truefalse,
    "./islands/_settings.ts": $_settings,
    "./islands/newclient.tsx": $newclient,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
