// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $browser from "./routes/browser.tsx";
import * as $index from "./routes/index.tsx";
import * as $singleplayer from "./routes/singleplayer.tsx";
import * as $Browser from "./islands/Browser.tsx";
import * as $Singleplayer from "./islands/Singleplayer.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/browser.tsx": $browser,
    "./routes/index.tsx": $index,
    "./routes/singleplayer.tsx": $singleplayer,
  },
  islands: {
    "./islands/Browser.tsx": $Browser,
    "./islands/Singleplayer.tsx": $Singleplayer,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
